-- Add cancel request columns to bets table
ALTER TABLE bets ADD COLUMN IF NOT EXISTS cancel_requested TINYINT(1) DEFAULT 0;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(255) DEFAULT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS cancel_requested_at DATETIME DEFAULT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS cancel_approved_by VARCHAR(100) DEFAULT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS cancel_approved_at DATETIME DEFAULT NULL;
